# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Spotify' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Spotify
  nm_path = '../node_modules'
  rn_path = "#{nm_path}/react-native"
  
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    #'RCTActionSheet',
    'RCTAnimation',
    #'RCTGeolocation',
    'RCTImage',
    #'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    #'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # Add new pods below this line
  pod 'RNSpotify', :path => '../node_modules/rn-spotify-sdk'

  pod 'RNEventEmitter', :path => '../node_modules/react-native-events'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'


  target 'Spotify-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpotifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
